import type { Provider, ServiceRequest, ProviderResponse, Transaction, AuditLog } from "./types";

// ─── Mock Providers ──────────────────────────────────────────────
export const providers: Provider[] = [
  {
    id: "chef-mateo",
    name: "Chef Mateo Laurent",
    category: "chef",
    tagline: "French Mediterranean mastery in the world's most exclusive settings",
    description:
      "Chef Mateo Laurent brings over 15 years of Michelin-star experience from Paris and the Côte d'Azur to your private table. Specializing in modern French Mediterranean cuisine, he curates immersive dining experiences that celebrate local ingredients and classical technique. From intimate dinners for two to grand celebrations of twenty, each meal is a composed narrative.",
    destinations: ["Bahamas", "Turks and Caicos", "Miami", "Saint Barts"],
    tags: ["French", "Mediterranean", "Michelin", "Private Dining", "Seafood", "Wine Pairing"],
    capacity: 20,
    priceFrom: 2800,
    priceCurrency: "USD",
    availability: "available",
    status: "approved",
    imageUrl: "/chef_mateo.png",
    galleryImages: ["/images/chef-mateo-1.jpg", "/images/chef-mateo-2.jpg", "/images/chef-mateo-3.jpg"],
    cuisineStyle: "French Mediterranean",
    rating: 4.9,
    completedServices: 87,
    responseTime: "< 2 hours",
  },
  {
    id: "chef-amara",
    name: "Chef Amara Silva",
    category: "chef",
    tagline: "Latin fine dining elevated to extraordinary heights",
    description:
      "Chef Amara Silva is a celebrated force in contemporary Latin fine dining, having trained under three James Beard Award-winning chefs across Santiago, Bogotá, and New York. Her approach melds bold South American flavors with refined European plating, creating menus that feel both grounded and transcendent. She is particularly sought after for bespoke tasting menus and destination dinner experiences.",
    destinations: ["Chile", "Caribbean", "Miami", "Bahamas", "Colombia"],
    tags: ["Latin", "Fine Dining", "Tasting Menu", "Fusion", "Ceviche", "Plant-Based Options"],
    capacity: 16,
    priceFrom: 2200,
    priceCurrency: "USD",
    availability: "limited",
    status: "approved",
    imageUrl: "/chef_amara.png",
    galleryImages: ["/images/chef-amara-1.jpg", "/images/chef-amara-2.jpg"],
    cuisineStyle: "Latin Fine Dining",
    rating: 4.8,
    completedServices: 62,
    responseTime: "< 3 hours",
  },
  {
    id: "chef-kenji",
    name: "Chef Kenji Morita",
    category: "chef",
    tagline: "Japanese tasting menus of rare precision and artistry",
    description:
      "Chef Kenji Morita studied under a Living National Treasure in Kyoto before developing his craft across Singapore, Dubai, and the Maldives. His tasting menus are composed as a sequence of moments — each course a conversation between season, place, and memory. Working with hyper-seasonal produce and responsibly sourced seafood, Kenji creates experiences that redefine what private dining can mean.",
    destinations: ["Maldives", "Dubai", "Singapore", "Tokyo", "Bahrain"],
    tags: ["Japanese", "Omakase", "Tasting Menu", "Wagyu", "Sustainable", "Sake Pairing"],
    capacity: 12,
    priceFrom: 3500,
    priceCurrency: "USD",
    availability: "available",
    status: "approved",
    imageUrl: "/chef_kenji.png",
    galleryImages: ["/images/chef-kenji-1.jpg", "/images/chef-kenji-2.jpg"],
    cuisineStyle: "Japanese Omakase",
    rating: 5.0,
    completedServices: 44,
    responseTime: "< 4 hours",
  },
  {
    id: "villa-marea",
    name: "Villa Maréa",
    category: "villa",
    tagline: "Barefoot luxury where the Atlantic meets the shore",
    description:
      "Villa Maréa is a masterpiece of tropical modernism on the northern shore of the Bahamas. With five oceanfront suites, an infinity pool that dissolves into the sea, and a private beach, it is the ultimate expression of understated luxury. Full staff service, a dedicated house manager, and curated culinary experiences are available on request. The property accommodates 10 guests with absolute privacy.",
    destinations: ["Bahamas"],
    tags: ["Beachfront", "Infinity Pool", "Full Staff", "Private Beach", "Boat Dock", "Chef Service"],
    capacity: 10,
    priceFrom: 12000,
    priceCurrency: "USD",
    availability: "available",
    status: "approved",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=2075&auto=format&fit=crop",
    galleryImages: ["/images/villa-marea-1.jpg", "/images/villa-marea-2.jpg", "/images/villa-marea-3.jpg"],
    bedrooms: 5,
    beachfront: true,
    staffIncluded: true,
    luxuryTier: "ultra-luxury",
    rating: 4.9,
    completedServices: 31,
    responseTime: "< 6 hours",
  },
  {
    id: "villa-azul",
    name: "Casa Azul Private Estate",
    category: "villa",
    tagline: "Caribbean grandeur veiled in total exclusivity",
    description:
      "Casa Azul Private Estate sits on a private peninsula in the Eastern Caribbean, offering panoramic views of turquoise waters from every angle. The six-bedroom main residence features a dramatic arrival courtyard, a wine cellar with over 800 labels, and a spa suite with direct ocean access. A dedicated concierge, private chef arrangement, and water sports program are available for all guests.",
    destinations: ["Caribbean", "Turks and Caicos"],
    tags: ["Peninsula", "6 Bedrooms", "Wine Cellar", "Spa", "Water Sports", "Concierge"],
    capacity: 14,
    priceFrom: 18000,
    priceCurrency: "USD",
    availability: "limited",
    status: "approved",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop",
    galleryImages: ["/images/villa-azul-1.jpg", "/images/villa-azul-2.jpg"],
    bedrooms: 6,
    beachfront: true,
    staffIncluded: true,
    luxuryTier: "ultra-premium",
    rating: 4.8,
    completedServices: 19,
    responseTime: "< 8 hours",
  },
  {
    id: "villa-solaris",
    name: "Villa Solaris",
    category: "villa",
    tagline: "A Mediterranean crown on the Ionian coast",
    description:
      "Villa Solaris is a historic Mediterranean estate perched above the Ionian sea, offering four luxury suites, a cliff-edge pool, and olive groves that have been in cultivation for over 200 years. The property combines 19th-century Venetian architecture with contemporary Italian interior design. Private boat access, bespoke culinary programming, and curated cultural excursions are all available through the estate's concierge team.",
    destinations: ["Mediterranean", "Morocco", "Greece"],
    tags: ["Mediterranean", "Historic", "Cliff-edge Pool", "Olive Groves", "Cultural", "Boat Access"],
    capacity: 8,
    priceFrom: 9500,
    priceCurrency: "USD",
    availability: "available",
    status: "approved",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
    galleryImages: ["/images/villa-solaris-1.jpg", "/images/villa-solaris-2.jpg"],
    bedrooms: 4,
    beachfront: false,
    staffIncluded: false,
    luxuryTier: "luxury",
    rating: 4.7,
    completedServices: 25,
    responseTime: "< 12 hours",
  },
];

// ─── Mock Requests ───────────────────────────────────────────────
export const sampleRequest: ServiceRequest = {
  id: "req-001",
  clientId: "client-001",
  clientName: "Alexandra M.",
  category: "chef",
  destination: "Bahamas",
  dateFrom: "2024-06-12",
  dateTo: "2024-06-18",
  guests: 8,
  budget: "premium",
  notes: "Looking for a Mediterranean dining experience across 4 evenings. Seafood emphasis preferred. We have one guest with a nut allergy.",
  status: "options_ready",
  createdAt: "2024-05-28T10:30:00Z",
  updatedAt: "2024-05-29T14:22:00Z",
  meals: ["Dinner"],
  cuisinePreference: "Mediterranean",
  dietaryRestrictions: "Nut allergy (one guest)",
  occasion: "Anniversary celebration",
  responses: [
    {
      id: "resp-001",
      requestId: "req-001",
      providerId: "chef-mateo",
      providerName: "Chef Mateo Laurent",
      status: "accepted",
      proposedPrice: 3200,
      message: "It would be my honor to craft this experience for you. I specialize in exactly this style and have worked extensively in the Bahamas. I suggest a menu arc across the four evenings — from a fresh crudo opener to a grand bouillabaisse finale.",
      createdAt: "2024-05-28T15:45:00Z",
    },
    {
      id: "resp-002",
      requestId: "req-001",
      providerId: "chef-amara",
      providerName: "Chef Amara Silva",
      status: "accepted",
      proposedPrice: 2800,
      message: "The Bahamas is one of my favorite destinations to work in. My Latin-Mediterranean fusion would complement the setting beautifully. I can accommodate the nut allergy without any compromise to the menu.",
      createdAt: "2024-05-29T09:12:00Z",
    },
  ],
};

export const mockRequests: ServiceRequest[] = [
  sampleRequest,
  {
    id: "req-002",
    clientId: "client-002",
    clientName: "James H.",
    category: "villa",
    destination: "Turks and Caicos",
    dateFrom: "2024-07-05",
    dateTo: "2024-07-12",
    guests: 10,
    budget: "ultra-luxury",
    notes: "Anniversary trip. Prefer full staff and beachfront.",
    status: "paid",
    createdAt: "2024-05-20T08:00:00Z",
    updatedAt: "2024-05-30T16:00:00Z",
    bedrooms: 5,
    beachfront: true,
    staffPreference: true,
    luxuryTier: "ultra-luxury",
    selectedProviderId: "villa-azul",
  },
  {
    id: "req-003",
    clientId: "client-003",
    clientName: "Isabelle C.",
    category: "chef",
    destination: "Maldives",
    dateFrom: "2024-07-20",
    dateTo: "2024-07-27",
    guests: 4,
    budget: "premium",
    notes: "Intimate dinners. Japanese or Asian fusion preferred.",
    status: "awaiting_provider_responses",
    createdAt: "2024-06-01T11:00:00Z",
    updatedAt: "2024-06-01T11:00:00Z",
    meals: ["Dinner", "Lunch"],
    cuisinePreference: "Japanese / Asian Fusion",
  },
];

// ─── Mock Transactions ───────────────────────────────────────────
export const mockTransactions: Transaction[] = [
  {
    id: "txn-001",
    requestId: "req-002",
    providerId: "villa-azul",
    providerName: "Casa Azul Private Estate",
    clientId: "client-002",
    clientName: "James H.",
    amount: 126000,
    platformFee: 12600,
    currency: "USD",
    status: "paid",
    paidAt: "2024-05-30T16:00:00Z",
    createdAt: "2024-05-30T15:45:00Z",
    contactReleased: true,
  },
  {
    id: "txn-002",
    requestId: "req-001",
    providerId: "chef-mateo",
    providerName: "Chef Mateo Laurent",
    clientId: "client-001",
    clientName: "Alexandra M.",
    amount: 19200,
    platformFee: 1920,
    currency: "USD",
    status: "pending",
    createdAt: "2024-06-01T12:00:00Z",
    contactReleased: false,
  },
];

// ─── Mock Audit Logs ─────────────────────────────────────────────
export const mockAuditLogs: AuditLog[] = [
  { id: "log-001", event: "Request created", requestId: "req-001", clientId: "client-001", timestamp: "2024-05-28T10:30:00Z", actor: "Alexandra M." },
  { id: "log-002", event: "Provider matched", requestId: "req-001", providerId: "chef-mateo", timestamp: "2024-05-28T10:31:00Z", actor: "System" },
  { id: "log-003", event: "Provider accepted", requestId: "req-001", providerId: "chef-mateo", timestamp: "2024-05-28T15:45:00Z", actor: "Chef Mateo Laurent" },
  { id: "log-004", event: "Provider accepted", requestId: "req-001", providerId: "chef-amara", timestamp: "2024-05-29T09:12:00Z", actor: "Chef Amara Silva" },
  { id: "log-005", event: "Options ready — client notified", requestId: "req-001", timestamp: "2024-05-29T09:15:00Z", actor: "System" },
  { id: "log-006", event: "Payment completed", requestId: "req-002", timestamp: "2024-05-30T16:00:00Z", actor: "James H." },
  { id: "log-007", event: "Contact released", requestId: "req-002", timestamp: "2024-05-30T16:01:00Z", actor: "System" },
];

// ─── Admin Stats ─────────────────────────────────────────────────
export const adminStats = {
  totalRequests: 47,
  pendingProviderResponses: 12,
  revenueThisMonth: 284600,
  providersUnderReview: 3,
  completedPayments: 31,
  approvedProviders: providers.filter(p => p.status === "approved").length,
};

// ─── Provider Contact Info (hidden until payment) ─────────────────
export const providerContacts: Record<string, { phone: string; email: string; whatsapp: string }> = {
  "chef-mateo": { phone: "+1 (242) 555-0142", email: "mateo@laurent-culinary.com", whatsapp: "+12425550142" },
  "chef-amara": { phone: "+56 9 5555 0234", email: "amara@silvafinedining.com", whatsapp: "+56955550234" },
  "chef-kenji": { phone: "+65 9555 0387", email: "kenji@moritaomakase.com", whatsapp: "+6595550387" },
  "villa-marea": { phone: "+1 (242) 555-0492", email: "reservations@villamarea.com", whatsapp: "+12425550492" },
  "villa-azul": { phone: "+1 (649) 555-0278", email: "estate@casaazulprivate.com", whatsapp: "+16495550278" },
  "villa-solaris": { phone: "+30 210 555 0165", email: "concierge@villasolaris.com", whatsapp: "+302105550165" },
};
